server:
  port: 8080

spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:store
      username: cobb
      password: bboc

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  sql:
    init:
      username: cobb
      password: bboc
      schema-locations: classpath*:db/schema.sql
      data-locations: classpath*:db/data.sql

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
#        show_sql: true

logging:
  level:
    org.hibernate: info
    org.springframework: info